language: php

php:
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer update

script:
  - ./bin/localgoogle crawl
  - php php/inc/crawler.class.php
  - php php/inc/search.inc.php
  - php php/crawl.php
  - php php/start_crawler.php

matrix:
 fast_finish: true
